
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tobias
 */
public class TransactionForm extends javax.swing.JFrame {
    
    public enum TransactionType{
        CREATE, UPDATE, DELETE, EXTEND_VALIDITY
    }
    
    private User user;
    private TransactionType type;
    private MainControl control;
    
    private final static Logger LOG = Logger.getLogger("*");
    
    /**
     * Creates new form TransactionForm
     */
    public TransactionForm(MainControl control, TransactionType t, User u, String dbUser) {
        this.type = t;
        this.control = control;
        this.user = u;
        
        initComponents();
        
        if(t!=TransactionType.EXTEND_VALIDITY){
            lblExpDate.setVisible(false);
            lblTransData.setVisible(false);
            lblNewExpDate.setVisible(false);
            trbTerms.setVisible(false);
            seperator.setVisible(false);
        }
        
        lblOperator.setText(dbUser);
        
        switch(t){
            case CREATE:
                lblAmountReceived.setText("0,00");
                lblHeader.setText("Create new account '" +u.getUsername() +"':" );
                textAreaDescription.setText("Created account.");
                break;
            case UPDATE:
                lblAmountReceived.setText("0,00");
                lblHeader.setText("Edit account '" +u.getUsername() +"':" );
                textAreaDescription.setText("Edited account record.");
                break;
            case DELETE:
                lblAmountReceived.setText("0,00");
                lblHeader.setText("Delete account '" +u.getUsername() +"':" );
                textAreaDescription.setText("Account deleted.");
                break;
            case EXTEND_VALIDITY:
                lblHeader.setText("Extend account validity of '" +u.getUsername() +"':" );
                updateExpDateValues(0); //Method call.
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();
        lblTransData = new javax.swing.JLabel();
        lblExpDate = new javax.swing.JLabel();
        seperator = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDescription = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        lblOperator = new javax.swing.JLabel();
        trbTerms = new javax.swing.JSlider();
        lblNewExpDate = new javax.swing.JLabel();
        lblAmountReceived = new javax.swing.JLabel();

        setTitle("Complete transaction");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblHeader.setText("[Operation] on account [username]:");

        jLabel2.setText("Operator:");

        jLabel3.setText("Payment received: ");

        jLabel4.setText("Description:");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        lblTransData.setText("Transaction specific data:");
        lblTransData.setOpaque(true);

        lblExpDate.setText("New expiration date:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textAreaDescription.setColumns(20);
        textAreaDescription.setRows(5);
        textAreaDescription.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                textAreaDescriptionAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(textAreaDescription);

        jLabel7.setText("EUR");

        lblOperator.setText("username");

        trbTerms.setMaximum(2);
        trbTerms.setValue(0);
        trbTerms.setName("trbTerms"); // NOI18N
        trbTerms.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                trbTermsStateChanged(evt);
            }
        });

        lblNewExpDate.setText("2016-04-30");
        lblNewExpDate.setName("lbl"); // NOI18N

        lblAmountReceived.setText("10,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(seperator)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeader)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)))
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblExpDate)
                                .addComponent(lblTransData)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAmountReceived)
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel7))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOperator))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNewExpDate)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(trbTerms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblOperator))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(lblAmountReceived))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(54, 54, 54)
                                .addComponent(seperator, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTransData))
                    .addComponent(trbTerms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpDate)
                    .addComponent(lblNewExpDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnFinish))
                .addContainerGap())
        );

        jLabel2.getAccessibleContext().setAccessibleName("Description:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
        control.enableMain();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        int amount;
        if(lblAmountReceived.getText().equals("")){
            amount = 0;
        }else{
            try{
                amount = (int) (Double.parseDouble(lblAmountReceived.getText().replace(',', '.'))*100);
            }catch(NumberFormatException e){
                LOG.severe("Check number format. Exception: " + e.getMessage());
                return; 
            }
        }
        
        switch(type){
            case CREATE:
                control.commitCreate(user, textAreaDescription.getText(), amount);
                break;
            case UPDATE:
                control.commitUpdate(user, textAreaDescription.getText(), amount);
                break;
            case DELETE:
                control.commitDelete(user, textAreaDescription.getText(), amount);
                break;
            case EXTEND_VALIDITY:
                user.setExpirationDate(lblNewExpDate.getText());
                control.commitExtend(user, textAreaDescription.getText(), amount);
                break;
        }
        setVisible(false);
    }//GEN-LAST:event_btnFinishActionPerformed

    private void textAreaDescriptionAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_textAreaDescriptionAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_textAreaDescriptionAncestorAdded

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);
        control.enableMain();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
        control.enableMain();
    }//GEN-LAST:event_formWindowClosing
    
    private void trbTermsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_trbTermsStateChanged
         updateExpDateValues(trbTerms.getValue());
    }//GEN-LAST:event_trbTermsStateChanged
    
    /**
     * Updates all values of the form, according to the new number of terms selected.
     * @param terms 
     */
    void updateExpDateValues(int terms){
      //Process Changes of Number of Terms.
        //Get new ExpDate
       
        int oldterms = -1;
        //check if account is already extended
        for(int i = 0; i <2; i++){
            if(control.getNextExpDate(i).equals(user.getExpirationDate())){
                oldterms = i;
                break;
            }
        }
        
        lblNewExpDate.setText(control.getNextExpDate(terms));
        textAreaDescription.setText("Account validity extended until "+lblNewExpDate.getText()+".");
        NumberFormat formatter = new DecimalFormat("#0,00");     
        lblAmountReceived.setText(formatter.format(1000*(terms-oldterms)));  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFinish;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmountReceived;
    private javax.swing.JLabel lblExpDate;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblNewExpDate;
    private javax.swing.JLabel lblOperator;
    private javax.swing.JLabel lblTransData;
    private javax.swing.JSeparator seperator;
    private javax.swing.JTextArea textAreaDescription;
    private javax.swing.JSlider trbTerms;
    // End of variables declaration//GEN-END:variables
    
}

